### ISSUE TITLE
Gebäude Produktion - Shader

### ISSUE THREAD

**Issue by firoball** [Acknex/CommandAndLotter#27]
Gebäude sollen anhand einer Fortschritt Variable 0..1 eingeblendet werden.
Zunächst werden die Konturen als Art Hologramm eingeblendet, von unten nach oben (z Achse) fortschreitend:
![grafik](https://user-images.githubusercontent.com/4692010/59549526-3ed01480-8f5f-11e9-9064-fba22044f32b.png)

und anschließend wird von unten nach oben die eigentliche Textur überlagert.

Das Gebäude blendet sich also von unten nach ein, man sieht erst einen Teil Hologramm, im weiteren Fortschritt wird aus dem Hologramm die solid Textur, bis das Gebäude kompeltt sichtbar ist.

**Comment by Slin** [comment]
fertig, aber noch nichts zum raufwerfen da...

**Comment by Slin** [comment]
dONE
