### ISSUE TITLE
PIZZA

### ISSUE THREAD

**Issue by xwcg** [Acknex/CommandAndLotter#28]
Problem: Wir haben keine Pizza. Welche Pizza brauchen wir?

Bitte kommentieren mit der Pizzawahl

**Comment by firoball** [comment]
Pizza al Proscuitto e Funghi  (/) 33

**Comment by pjen** [comment]
Spaghetti Bolognese 
mit Hackfleischsauce

**Comment by evil-lemming** [comment]
Pizza Quattro Formaggi 28cm

**Comment by xwcg** [comment]
Pizza Alforno @ 33cm

**Comment by ikskuh** [comment]
Pizza Sucuk / 60cm

**Comment by sgpohl** [comment]
Vierkäse 33

**Comment by DragonKitten** [comment]
Pizza Spinachi Lachs /60cm

**Comment by Digital-NW** [comment]
Romana /60cm

**Comment by KorbiFraiser** [comment]
1x Pizza Hawaii /33cm

**Comment by Slin** [comment]
Pizza Paprika 33cm

**Comment by Hen-woll** [comment]
Pizza Margherita  /33cm

**Comment by xwcg** [comment]
Wird bestellt. Danke für die Teilnahme und guten Appetit.
