### ISSUE TITLE
Minimap interaktion

### ISSUE THREAD

**Issue by sgpohl** [Acknex/CommandAndLotter#39]
Mausklicks haben einen offset, Kamera wird zu weit südlich positioniert

**Comment by firoball** [comment]
Einheiten under dem Fog of War werden nicht ausgeblendet. Da fehlt noch eine Abfrage:

	TILE* tile = mapGetTileFromVector(mapGetCurrent(), &entity->x);
	if (tile->visibility == FOW_SCOUTED) {/*draw me */}

**Comment by ikskuh** [comment]
> Mausklicks haben einen offset, Kamera wird zu weit südlich positioniert

Ich glaube, die Kamera fokussiert den angeklickten Punkt, passt also meiner Meinung nach

**Comment by pjen** [comment]
Jup hatte da bereits am Ende an einer anderen Lösung gearbeitet, extra Panel auf der Minimap das getrechted wird vom Camera Punkt, bis zum Target. Bin damit aber damit bisher nicht weitergekommen und Montag-Mittwoch schaffe ich da nichts

**Comment by ikskuh** [comment]
Ich bin grade schon dran, mir das mit der MiniMap mal anzugucken

**Comment by ikskuh** [comment]
@pjen Spricht was dagegen, die Minimap als Bitmap statt als Panel zu rendern?
Ich würde einfach die Map für eine Auflösung von 1280x720 anpassen und hochskalieren geht dann über das `NOFILTER` Flag...
Damit könnte man sowas wie "unaufgedeckte map" auch gleich mit in die MiniMap mit aufnehmen

**Comment by pjen** [comment]
Im Moment werden die Einheiten mit pan_setwindow angezeigt, da ich für etwas anderes keine Zeit mehr hatte. Du kannst das gern so ändern, so ist das sowieso eher suboptimal. Wie möchtest du dann die "dots" auf der Karte anzeigen?

**Comment by ikskuh** [comment]
Ich würde die BMAP der Karte direkt mit Pixeln füllen. Mit [`bmap_to_format`](www.conitec.net/beta/abmap_to_format.htm) kann man auch direkt die Pixel über die Bitmap verwursten, ohne setpixel oder ähnliches => sehr schnell

**Comment by ikskuh** [comment]
@pjen Ich hab die Karte jetzt mal auf bitmap rendering umgestellt. Mein Problem:
Ich versteh nicht ganz, wie ich die Minimap jetzt in ihre beiden Fensterchen reinziehen soll... Willst du das übernehmen oder soll ich den Teil komplett neu machen? (Also das Minimap anzeigen)

**Comment by ikskuh** [comment]
Minimap fixed.
