### ISSUE TITLE
HUD Icon Baumenü - Gebäude

### ISSUE THREAD

**Issue by pjen** [Acknex/CommandAndLotter#4]

**Comment by pjen** [comment]
* Für jede Einheit ein Icon
* Ein delete/abreißen Icon für Gebäude
* Ein "leeres" Icon damit dort ein Counter reinkommen kann

**Comment by ikskuh** [comment]
@pjen Es benötigt noch einen Menüpunkt für die Bank of Zorro, zudem stimmen die Icons nicht mit der Gebäude-ID überein

**Comment by pjen** [comment]
Jup Muss an die jetzigen Gegebenheiten angepasst werden
* Turm nicht korrekt
* Bank
* Eseldingens muss an den Stil der anderen angepasst werden
* Kosten oben statt blitz anzeigen

**Comment by ikskuh** [comment]
Kannst du das machen oder fehlt dir da die Zeit dazu?

**Comment by pjen** [comment]
Ich werde schauen ob ich das heute Abend oder Donnerstag Abend schaffe (oder Samstag)

**Comment by firoball** [comment]
Die circle Menüs benötigen auch ein Update, da es jetzt die Skulls als Mining Einheit (Über Bank of Zorro) gibt. Die hab ich derzeit einfach als CBabe reingefrickelt, damit das Spiel beim Menüaufruf nicht crasht. Muss aber noch sauber implementiert werden.
Evtl kann @Hen-woll sich um die zugehörigen Grafiken kümmern

**Comment by ikskuh** [comment]
Baumenü und Circle Menüs sind fertig
